// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbqmnvkzvqmsshufawwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdicW1udmt6dnFtc3NodWZhd3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNzM4NDMsImV4cCI6MjA3Njc0OTg0M30.3jH_F0hg1ibgw6WA7wDGwZd9NbVlOWO6S2k2balK-K0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});